### ISSUE TITLE
Which version of pytorch

### ISSUE THREAD

**Issue by Steve-Tod** [yifita/deep_cage#1]
Hi, thanks for sharing the code. What's the version of Pytorch you are using? There is no PyTorch in environment.yml or requirements.txt.

**Comment by Steve-Tod** [comment]
Also, what's the version of cuda you are using?

**Comment by yifita** [comment]
Hi, pytorch and cuda version is specified in the pytorch_points submodule, on which this project depend.

https://github.com/yifita/pytorch_points/blob/57e54090a590fa23ff1c7516ccc77ba3d527e401/requirements.txt

**Comment by Steve-Tod** [comment]
I use PyTorch 1.13.1, Cuda 10.0, python 3.7. After I compiled the pytorch_points, I run the code which import from pytorch_points, I got the following error:
/orion/u/jiangthu/projects/deep_cage/pytorch_points/pytorch_points/_ext/sampling.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationERKSs
Have you ever met this?

**Comment by Steve-Tod** [comment]
Thank you! It works.

**Comment by Steve-Tod** [comment]
By the way, can you also share the training script as a reference?
