### ISSUE TITLE
`faiss_knn, group_knn` not implemented in `pytorch_points.network.operations.py` 

### ISSUE THREAD

**Issue by KnightOfTheMoonlight** [yifita/deep_cage#10]
Hi, Yifan,

Thanks for sharing this great work. However, when I finished the setup, and run the demo code, I found the following error,
```
ImportError: cannot import name 'faiss_knn' from 'pytorch_points.network.operations' (xxx/deep_cage/pytorch_points/pytorch_points/network/operations.py)
```
I have doublechecked your [pytorch_points](https://github.com/yifita/pytorch_points) project. There are no `faiss_knn` or `group_knn` function in the [operations.py](https://github.com/yifita/pytorch_points/blob/master/pytorch_points/network/operations.py) script.

**Comment by yifita** [comment]
Hi @KnightOfTheMoonlight thanks for using the code. 
You need to use the pytorch_points version reference in the submodule, which contains these two functions.

To do that, make sure that you clone the neural cage repo with `--recursive` option, i.e.
`git clone --recursive https://github.com/yifita/deep_cage.git`

**Comment by wishinghao** [comment]
hello, I am interesting in this code, and want to use it to help my research project.
But I found the same error . There are no faiss_knn or group_knn function in the operations.py script.
I use `--recursive` to download but :
Error downloading object: data/processed_shapenetseg/test_Chair_100_2500.pkl (9554bc7): Smudge error: Error downloading data/processed_shapenetseg/test_
Chair_100_2500.pkl (9554bc76b605d31575be0c007a18d132916af21799fb148fa551f6b919310bf4): batch response: This repository is over its data quota. Account r
esponsible for LFS bandwidth should purchase more data packs to restore access.
                                                                            
Errors logged to /data4/honghu/deep_cage/.git/lfs/logs/20210728T221331.090982032.log
Use git lfs logs last to view the log.            
error: external filter 'git-lfs filter-process' failed                      
fatal: data/processed_shapenetseg/test_Chair_100_2500.pkl: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.                
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

So I get `pytorch_points ` submodule by hand, download the .zip file. But there is no faiss_knn or group_knn function in script
