### ISSUE TITLE
multifold gen

### ISSUE THREAD

**Issue by Colin97** [yifita/deep_cage#12]
Hi,

Thanks for the great work! I was wondering the meaning of "MultiFoldPointGen", since you only use the last [fold](https://github.com/yifita/deep_cage/blob/e0db2175128c7aaf3add513f3eca1afe90b8e8e5/networks.py#L411). Could you please explain that?

Thanks,

**Comment by yifita** [comment]
Hi Colin,

Thanks for paying such close attention. To me, it meant to refer to the fact that the network **has** multiple "folds".
