### ISSUE TITLE
pytorch version

### ISSUE THREAD

**Issue by hjwdzh** [yifita/deep_cage#2]
I followed the instructions for installation.

It seems that environment.yml does not automatically help me install pytorch -- so after I activate the pytorch-all environment, I install manually with pip install pytorch (which is 1.4).

Then I got this error "pytorch_points/_ext/torch_batch_svd.cpp:18:75: error: ‘THCState_getCurrentBlasHandle’ was not declared in this scope".

I believe this could be caused by wrong version of pytorch. Any suggestions for solving this issue?

Thanks.

**Comment by hjwdzh** [comment]
For pytorch 1.2 I got

pytorch_points/_ext/torch_batch_svd.cpp:59:33: error: expected primary-expression before ‘float’
     const auto d_A = A.data_ptr<float>();

**Comment by yifita** [comment]
( Related to #1  )
Updated the installation instruction, now the environment is created from `pytorch_points` subfolder.
Also updated pytorch_points, which uses pytorch 1.4.0 and should have these compilation errors resolved.

commit https://github.com/yifita/deep_cage/commit/f012fdadbdb0306562e09f364d0f2af243624fb2

**Comment by hjwdzh** [comment]
Thanks!
