### ISSUE TITLE
links on weight files broken

### ISSUE THREAD

**Issue by uingue** [yifita/deep_cage#6]
Hi, it looks like a very nice work. 
Recently I clone the repo via git lfs and got some errors like:
```
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
```
It seems that the lfs links to some files broken. 
Maybe using Google Drive or some free storage could help? 

Also, could you please offer the training script? 

Thanks!

**Comment by yifita** [comment]
Hi @uingue , thanks for the hint. 
I've uploaded the models to a permanent address https://igl.ethz.ch/projects/neural-cage/trained_models.zip
