### ISSUE TITLE
setup.py problem

### ISSUE THREAD

**Issue by camelliawb** [yifita/deep_cage#7]
Hi, thanks for sharing the code. When I run setup.py I met some errors,can you help me ?

pytorch_points/_ext/torch_batch_svd.cpp:65:63: error: ‘cusolverDnDestroyGesvdjInfo’ was not declared in this scope
     auto params = unique_allocate(cusolverDnCreateGesvdjInfo, cusolverDnDestroyGesvdjInfo);
                                                               ^
pytorch_points/_ext/torch_batch_svd.cpp:66:66: error: ‘cusolverDnXgesvdjSetTolerance’ was not declared in this scope
     auto status = cusolverDnXgesvdjSetTolerance(params.get(), tol);
                                                                  ^
pytorch_points/_ext/torch_batch_svd.cpp:68:68: error: ‘cusolverDnXgesvdjSetMaxSweeps’ was not declared in this scope
     status = cusolverDnXgesvdjSetMaxSweeps(params.get(), max_sweeps);
                                                                    ^
pytorch_points/_ext/torch_batch_svd.cpp:70:63: error: ‘cusolverDnXgesvdjSetSortEig’ was not declared in this scope
     status = cusolverDnXgesvdjSetSortEig(params.get(), is_sort);

**Comment by yifita** [comment]
Hi, seems to me that you cuda directory is not set correctly.
You need to make sure that your cuda directory is set correctly. For me i'm using cuda 10.1, stored under `/usr/local/cuda`. Then I set the following environment variables in `~/.zshrc`:
```bash
export PATH=/usr/local/cuda/bin${PATH:+:${PATH}}
export LD_LIBRARY_PATH=/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
```
